### ISSUE TITLE
Elapsed time not showing for successful output

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-server#73]
![image](https://user-images.githubusercontent.com/211271/94906893-2d35b780-0497-11eb-83e2-f0424bdc479d.png)

Job#108 took 1h 10m, for example

**Comment by ghickman** [comment]
We're overwriting `Job.started_at` on every save of an instance (instead of only when `started_at` hasn't been set).  When we come to render elapsed time we only show hours, minutes, and seconds when they've truthy (ie 1+) so we get no output here.

We're going to let job-runner handle setting `started_at` and `completed_at` which will fix this.
