### ISSUE TITLE
Suggestion: JobRequests should include specific git-sha

### ISSUE THREAD

**Issue by evansd** [opensafely/job-server#88]
Now that we have github auth, the job-server can determine the sha of the branch head which the user wants to run. This can then be included on the JobRequest.

I think the advantages of making it clear and deterministic which version of the code will run outweigh the convenience (in some cases) of automatically picking up code changes pushed after the job is requested.

We can still support modifying the commit for dependant jobs which have been scheduled but not yet run if we want to. (It should just be enough to modify the commit field on the JobRequest, which will then get synced back to the job-runner.) But this would be something explicitly requested by the user rather than implicit behaviour.

**Comment by ghickman** [comment]
Agreed.

I think we might want to track both the branch and SHA though?  Then give the user a button to bump a JobRequest's SHA to HEAD for the Workspace's Branch?

**Comment by ghickman** [comment]
Relatedly, should we move `branch|sha` onto `JobRequest` and leave `Workspace` to model a Repo?

**Comment by evansd** [comment]
I think that would make sense. The way I see it, each JobRequest has a `sha` which is set when its first created but may change later. When the job-runner kicks off a job it checks the current `sha` on (its copy of) the JobRequest and uses that, storing that `sha` on the Job.

Does that make sense?

**Comment by ghickman** [comment]
Definitely, and it tracks well with how we're splitting up the responsiblities of `JobRequest` and `Job` too.  I'm in the process of moving `branch` from `Workspace` to `JobRequest` (#95), which we can use to define `JobRequest`s `sha`.

Shall we say, at least for now, that once a `JobRequest` has been acked (ie has dependant `Job`s), we'll consider its `branch` (and thus `sha`) locked?  Keeps things simple, etc.

**Comment by sebbacon** [comment]
This all makes sense.

Bearing in mind our priority use-case at the moment is to support iterative development, I think it's also correct that a Workspace doesn't care about `sha` and the default behaviour for a new `JobRequest` should be for it to be the current tip of the ref.

Later, as discussed, we will want to think about "production" mode at some point (when the job-runner takes into account the `sha` when deciding whether an action needs (re)running) and we could perhaps require a tag refspec rather than a branch in such cases.
