### ISSUE TITLE
Roll out JobRequest to Runner

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-server#99]
The move to `JobRequest` is a breaking change for job-runner.

job-runner currently talks to job-server via the `/api/jobs` endpoint.  As per discussions in #84 we want to have job-server own `JobRequest`s and job-runner own `Job`s.  However the introduction of `JobRequest` and our general sync protocol from #84 are turning out to be large enough that we could face some significant downtime of the job-server <-> job-runner link without a migration strategy.

The high-level changes introduced to job-server so far:
* `Job`s are owned by a `JobRequest`
* A given `JobRequest` is how `Job`s are referenced.

I think we can define an initial set of changes which leave the job-server <-> job-runner link intact:
1. Add `job_request_id` to job-runner's `Job`.
1. Continue to have job-runner talk to `/api/jobs/` but translate all requests to the relevant `JobRequest`.

This creates the minimal number of changes to job-runner so work there isn't stalled dealing with API changes, while job-server can start deploying changes again.

**Comment by ghickman** [comment]
@sebbacon & @evansd – have I missed anything here?  I don't have a good read on the amount of work required to add `Job.request_id` in job-runner, does that seem like a big chunk of work?

**Comment by sebbacon** [comment]
I'm not sure, thinking about this in a skimming-kind-of-way due to time constraints...

How would `job_request_id` be different from the current `needed_by`?

The job runner main loop is "give me all Jobs marked as not started".  It then marks them as `started` (making the field double up as also meaning `acked`, potentially adds a bunch of dependencies as Jobs which are pushed to the server, and then if there are dependencies, reverts the original job to not-`started`.

So on the polling, we want the server to translate JobRequests into the expected `job_spec` format. The acking/`started` stuff can still apply to jobs.  In fact if JobRequests were to start by making a corresponding Job that might be the shim we need?

Sorry, I should think this through properly but I have to think about snotty noses quickly now before school pickup! Does that help?

**Comment by ghickman** [comment]
> How would job_request_id be different from the current needed_by?

`needed_by` models "which `Job` required the current `Job`", and is effectively serialising edges onto the parent part of each edge.  With that comes that at least one `Job` in the graph will no `needed_by` value.

`job_request_id` models "which request-from-a-user did this `Job` come from".

> if JobRequests were to start by making a corresponding Job

We've talked that one through a few times and decided that's a boundary we don't want to cross, maybe the pragmatic option is to cross it in the interim?  If we add the `job_request_id` field to `Job`s in the job-runner then dependant `Job`s being created via the API can still be tied to a `JobRequest` in job-server.

**Comment by evansd** [comment]
Thanks @ghickman, sorry I haven't got to this earlier. Thinking about this more, I don't know that there really is a gradual migration option here. It's not so much about the API as the fact that the job-runner itself needs to undergo some significant structural alternations. For instance, at the moment it relies on the job-server to store its state for it but we're planning to give it its own database. I can't quite get my head round how it works to do this gradually.

**Comment by ghickman** [comment]
@evansd – I don't think the lack of local state changes much at the moment.  My initial priority is to unblock the deployment of the `JobRequest` changes to job-server (since many features/fixes are gated on that existing).  If I've understood the situation in job-runner correctly then I think we can add `job_request_id` to the `Job` payloads coming from `/api/jobs/` and job-runner will pass them around without issue?

If that's the case then incoming POST/PATCH/PUT requests will contain it too and we can tie `Job`s back to the `JobRequest`.

**Comment by evansd** [comment]
Ah OK, I get you now. Yes, hopefully that should work.

**Comment by ghickman** [comment]
v2 handles this for us 🎉
